name             "kernel"
maintainer       "The Cloudscaling Group, Inc."
maintainer_email "pd@cloudscaling.com"
license          "Apache 2.0"
description      "Description of this Cookbook"
version          "0.1"
