#!/usr/bin/python

import json
import requests

ips = []

f =  open('/etc/chef/solo.rb', 'r')
for line in f:
  x = line.find("json_attrib")
  if x >=0:
    y = line.find("http://")
    z = line.find("/machine/")
    zmip = line[y+7:z]

URL = "http://" + zmip + "/machine/search?view=chef"
machines = requests.get(URL).json()

for machine in machines:
  if machine['design'] == "compute_node":
    ips.append(machine['application_ip'])

#sort by ip
for i in range(len(ips)):
    ips[i] = "%3s.%3s.%3s.%3s" % tuple(ips[i].split("."))
ips.sort()
for i in range(len(ips)):
    ips[i] = ips[i].replace(" ", "")
    print ips[i]
