maintainer       "Dan Sneddon"
maintainer_email "dan@cloudscaling.com"
description      "Installs/Configures Quagga"
version          "0.0.2"
supports         "ubuntu"
depends          "ubuntu"
recipe           "quagga::app_ecmp", "Configures Quagga daemons to announce the load-balancer IP"
recipe           "quagga::natter", "Configures Quagga for Natters to detect failure scenarios and redirect traffic to working natters"
name             "quagga"
