maintainer        "Blake Barnett"
maintainer_email  "bdb@cloudscaling.com"
license           "Apache 2.0"
description       "Sets up sources for ubuntu"
version           "1.0.0"
depends           "apt"
supports          "ubuntu"
recipe            "ubuntu", "Sets up sources for the node's ubuntu release"
name              "ubuntu"
