if RUBY_VERSION =~ /1.9/
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

source 'https://rubygems.org'

gem 'chef', '>= 10.26', '< 11'
gem 'foodcritic'
gem 'strainer'
