name              "graphite"
maintainer        "Abhishek Chanda"
maintainer_email  "abhishek@cloudscaling.com"
license           "Apache 2.0"
description       "Installs and configures Graphite."
version           "0.1.5"
recipe            "graphite", "Installs and configures Graphite and all of its components"
recipe            "graphite::carbon", "Installs and configures Carbon"
recipe            "graphite::dashboard", "Installs and configures the Graphite dashboard"
depends           "apache2"
